import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

export default function Layout({title, children}) {
  return (
    <>
        <Head>
            <title>{title ? title + ' -AntzCart' : 'AntzCart'}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='flex min-h-screen flex-col justify-between '>
            <header>
                <header>
                    <nav className='flex h-12 px-4 justify-between items-center shadow-md'>
                        <Link href='/'>
                            <a className='text-lg font-bold'>AntzCart</a>
                        </Link>
                        <dev>
                            <Link href='/cart'><a className='p-2'>Cart</a></Link>
                            <Link href='/login'><a className='p-2'>Login</a></Link>
                        </dev>
                    </nav>
                </header>
            </header>
            <main className='container m-auto mt-4 px-4'>{children}</main>
            <footer className='flex justify-center items-center h-10 shadow-inner'>footer</footer>
        </div>
    </>
  )
}
