const data = {
    products : [
        {
            name :'Free product',
            slug :'product1',
            catagory :'cat1',
            image :'/images/i1.jpg',
            price : 1000,
            brand : 'rasberry pi',
            rating : 4.5,
            numReviews : 8,
            countInStack : 20,
            description : 'This product description',
        },
        {
            name :'Free product',
            slug :'product2',
            catagory :'cat2',
            image :'/images/i2.jpg',
            price : 1000,
            brand : 'brand1',
            rating : 4.5,
            numReviews : 8,
            countInStack : 20,
            description : 'This product description',
        },
        {
            name :'Free product',
            slug :'product3',
            catagory :'cat2',
            image :'/images/i3.jpg',
            price : 1000,
            brand : 'brand2',
            rating : 4.5,
            numReviews : 8,
            countInStack : 20,
            description : 'This product description',
        },
        {
            name :'Free product',
            slug :'product4',
            catagory :'cat1',
            image :'/images/i4.jpg',
            price : 1000,
            brand : 'rasberry pi',
            rating : 4.5,
            numReviews : 8,
            countInStack : 20,
            description : 'This product description',
        },
        {
            name :'Free product',
            slug :'product5',
            catagory :'cat2',
            image :'/images/i5.jpg',
            price : 1000,
            brand : 'brand1',
            rating : 4.5,
            numReviews : 8,
            countInStack : 20,
            description : 'This product description',
        },
        {
            name :'Free product',
            slug :'product6',
            catagory :'cat2',
            image :'/images/i6.jpg',
            price : 1000,
            brand : 'brand2',
            rating : 4.5,
            numReviews : 8,
            countInStack : 20,
            description : 'This product description',
        },
    ]

};

export default data;